name: Build iOS App (Unsigned IPA)

on:
  push:
    branches:
      - main  

jobs:
  build-ios:
    runs-on: macos-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x  

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS App
        run: |
          cd ios
          xcodebuild -workspace Easy.xcworkspace \
            -scheme Easy \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $GITHUB_WORKSPACE/build/Easy.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            archive

      - name: Export Unsigned IPA
        run: |
          cd ios
          mkdir -p Payload
          cp -r $GITHUB_WORKSPACE/build/Easy.xcarchive/Products/Applications/Easy.app Payload/
          zip -r Easy.ipa Payload

      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: Easy.ipa
          path: ios/Easy.ipa
